name: GitHub Action Learning

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Check Python version
        run: python -c "import sys; print(sys.version)"

      - name: install requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest tests/tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Upload pytest results
        uses: actions/upload-artifact@v4.2.0
        if: ${{ always() }}
        with:
          name: pytest-results
          path: junit/test-results.xml

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4.2.0
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish to pypi
    needs:
      - build
    runs-on: windows-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ty_python_learning
    permissions:
      id-token: write

    steps:
      - name: Download the Stored distribution packages
        uses: actions/download-artifact@v4.1.1
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1