name: GitHub Action Learning

on: [push]

jobs:
  learning:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python version
        run: python -c "import sys; print(sys.version)"

      - name: install requirements
        run: |
          python -m pip install --upgrade pip build
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest tests/tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Upload pytest results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results.xml

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __TOKEN_GITHUB_ACTIONS__
          password: ${{ secrets.PYPI_API_TOKEN }}
