name: Test

on:
  push:
    branches-ignore:
      - 'release/**'
  pull_request:
    branches-ignore:
      - 'release/**'

jobs:
  Test:
    strategy:
      matrix:
        python: [ '3.12' ]
        platform: [ 'ubuntu-latest' ]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Check Python version
        run: python -c "import sys; print(sys.version)"

      - name: install requirements
        run: |
          python -m pip install --upgrade pip build
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest tests/tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Upload pytest results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.2.0
        with:
          name: pytest-results
          path: junit/test-results.xml
